### ISSUE TITLE
test_verilog_sim bug

### ISSUE THREAD

**Issue by alexcarsello** [rsetaluri/gemstone#1]
test_global_controller_verilog_sim in Garnet fails because it cannot locate the cmd.tcl file for irun. It's expecting the file to be located at garnet/common/irun/cmd.tcl, but it's only in Gemstone. I can fix it by copying the file into Garnet, but it'd be better for Gemstone to handle this.

Note that there were other bugs in the test, but those have been fixed in the repair_tests branch in Garnet.

**Comment by rsetaluri** [comment]
@alexcarsello can you verify this has been fixed by the latest commits?

**Comment by alexcarsello** [comment]
Yep, it's fixed. Thanks.
